### ISSUE TITLE
TypeError: Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by rejas** [morris/vinyl-ftp#12]
After switching from gulp-ftp, I have this task specified according to your docs:

```
gulp.task('ftp', function () {
    return gulp.src('.')
        .pipe(plugins.prompt.prompt({
            type: 'password',
            name: 'pw',
            message: 'enter ftp password'
        }, function(result) {
            var conn = ftp.create({
                host:     config.ftp.host,
                user:     config.ftp.user,
                password: result.pw,
                parallel: 1,
                log: gutil.log
            });

            return gulp.src([dirs.dist + '**/*'], { base: '.', buffer: false } )
                .pipe(conn.newer('/')) // only upload newer files
                .pipe(conn.dest('/'));
        }));
});
```

but only get this error when running it:

```
[gulp] Starting 'upload'...
[?] enter ftp password: *******
[gulp] Finished 'upload' after 7.05 s
[19:27:01] CONN 
[19:27:01] READY
[19:27:01] MLSD  /dist
/Volumes/USR/xxxx/Projects/Homepage/node_modules/vinyl-ftp/lib/mlsd.js:93
          var year = modify.substr( 0, 4 );
                           ^
TypeError: Cannot read property 'substr' of undefined
    at /Volumes/USR/xxxx/Projects/Homepage/node_modules/vinyl-ftp/lib/mlsd.js:93:28
```

**Comment by jandob** [comment]
Had the same error. 
It occurs when the ftp server response to a directory listing request (mlsd) has keys with first letter uppercase. 
e.g.
```
 { name: '.',
  Type: 'cdir',
  Modify: '20150423191421',
  Unique: '04c8000c0de7b18c',
  Perm: 'cmpdfe' }
```

**Comment by rejas** [comment]
yes, that fix of yours works for me. would be awesome if that could be merged in one form or another :-)

**Comment by morris** [comment]
thanks for reporting and fixing this. i merged the fix and will release to npm soon :)

**Comment by rejas** [comment]
awesome!

**Comment by morris** [comment]
Fixed at v0.4.1

**Comment by Roquie** [comment]
Hello! Error showing again (version 0.4.1)... My output:
```cls
Roquie-mac:slk-nt.lc max$ gulp deploy
[13:29:58] Using gulpfile ~/htdocs/webprojects/secret.lc/gulpfile.js
[13:29:58] Starting 'deploy'...
[13:29:58] CONN 
[13:29:58] CONN 
[13:29:58] CONN 
[13:29:58] CONN 
[13:29:58] CONN 
[13:29:58] CONN 
[13:30:02] READY
[13:30:02] MLSD  /Users/roquie/htdocs/webprojects/secret.lc/public
[13:30:02] READY
[13:30:02] MLSD  /Users/roquie/htdocs/webprojects/public/js
[13:30:03] READY
[13:30:03] MLSD  /Users/roquie/htdocs/webprojects/secret.lc/public/js/includes
[13:30:03] MLSD  /Users/roquie/htdocs/webprojects/secret.lc/
[13:30:04] READY
[13:30:04] MLSD  /Users/roquie/htdocs/webprojects/secret.lc/public/css
[13:30:04] READY
[13:30:04] MLSD  /Users/roquie/htdocs/webprojects/secret.lc/public/img/f1/graph
[13:30:04] READY
[13:30:04] MLSD  /Users/roquie/htdocs/webprojects/secret.lc/public/css/includes
[13:30:05] MLSD  /Users/roquie/htdocs/webprojects
[13:30:05] MLSD  /Users/roquie/htdocs/webprojects/secret.lc/public/img/onetel
[13:30:05] MLSD  /Users/roquie/htdocs/webprojects/secret.lc/public/img/new-icons/oldest
[13:30:05] MLSD  /Users/roquie/htdocs/webprojects/secret.lc/public/img
[13:30:05] MLSD  /Users/roquie/htdocs
[13:30:06] MLSD  /Users/roquie
[13:30:06] MLSD  /Users
[13:30:06] MLSD  /
/Users/roquie/htdocs/webprojects/secret.lc/node_modules/vinyl-ftp/lib/mlsd.js:93
          var year = modify.substr( 0, 4 );
                           ^
TypeError: Cannot read property 'substr' of undefined
    at /Users/roquie/htdocs/webprojects/secret.lc/node_modules/vinyl-ftp/lib/mlsd.js:93:28
    at Array.map (native)
    at final (/Users/roquie/htdocs/webprojects/secret.lc/node_modules/vinyl-ftp/lib/mlsd.js:80:27)
    at Object.cb (/Users/roquie/htdocs/webprojects/secret.lc/node_modules/vinyl-ftp/lib/mlsd.js:150:9)
    at Parser.<anonymous> (/Users/roquie/htdocs/webprojects/secret.lc/node_modules/vinyl-ftp/node_modules/ftp/lib/connection.js:117:20)
    at Parser.emit (events.js:110:17)
    at Parser._write (/Users/roquie/htdocs/webprojects/secret.lc/node_modules/vinyl-ftp/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Parser.Writable.write (_stream_writable.js:217:11)

```

task:
```js
gulp.task( 'deploy', function() {

    var connection = ftp.create( {
        host:     process.env.FTP_HOST,
        user:     process.env.FTP_USERNAME,
        password: process.env.FTP_PASSWORD,
        parallel: 1,
        log: gutil.log
    } );

    // using base = '.' will transfer everything to /public_html correctly
    // turn off buffering in gulp.src for best performance
    return gulp.src(config.upload_globs, { base: '.', buffer: false } )
        //.pipe(plumber())
        //.pipe( connection.newer( process.env.FTP_BASEPATH ) ) // only upload newer files
        .pipe( connection.newerOrDifferentSize( process.env.FTP_BASEPATH ) );
} );

//config.upload_globs
/*
"public/js/**",
"public/css/**/**",
"public/img/**/**",
"public/fonts/**/**"
*/
```

Where am I wrong?

**Comment by morris** [comment]
Could you `console.log( buffer )` at mlsd.js, line 77 and paste the result so I can see how MLSD looks like on your server? Will be a lot, paste only the last MLSD. Another option is to send me FTP credentials for your server so I can test. mb@morrisbrodersen.de - thanks for reporting!

**Comment by jslaterTO** [comment]
I'm running in to the same issue - here's an example of what I get from `console.log(buffer)` on that line:

``` 
 .
 ..
 .htaccess
 js
 config
 images
 sass
 index.php
 pages
 css
```

Looking over the rest of that function, I get the impression there's some other data that should be there, but isn't?

**Comment by Roquie** [comment]
```cls
[20:23:17] MLSD  /production/secret.com/www/public
 .
 ..
 .htaccess
 .DS_Store
 index.php
 favicon.ico
 robots.txt
 fonts
 img
 js
 bower_components
 documents
 less
 css
```

mmm... normal. Correct. Can I help you with something else?

**Comment by morris** [comment]
Well that is odd, although it's [RFC-compliant](https://tools.ietf.org/html/rfc3659#section-7.2) not to return any additional info on the files. I'd expect something like

`modify=20150428075600;perm=flcdmpe;type=dir;unique=803U31A2007;UNIX.group=1113;UNIX.mode=0755;UNIX.owner=1240; img
modify=20150710224755;perm=flcdmpe;type=dir;unique=803U31A05CB;UNIX.group=1113;UNIX.mode=0755;UNIX.owner=1240; js
...`

It should work with LIST, however vinyl-ftp currently does not check if MLSD replies with or without `modify`. So the fix is: make `modify` optional in MLSD, then fall back to LIST if `modify` is not present. Will get to this in a few and release a fix for that. Thank you again for reporting! :)

**Comment by morris** [comment]
Got it, should be good at v0.4.2

**Comment by Roquie** [comment]
Good. Great job. All works fine. :+1:
