### ISSUE TITLE
missing module lodash

### ISSUE THREAD

**Issue by maxleistner** [morris/vinyl-ftp#21]
I get the following error trying to ```gulp deploy```
I installed lodash globally and in the project folder
```
module.js:338
    throw err;
          ^
Error: Cannot find module 'lodash._getnative'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/PATH_TO_MY_PROJECT/node_modules/gulp/node_modules/gulp-util/node_modules/lodash.template/node_modules/lodash.keys/index.js:9:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

```

**Comment by morris** [comment]
most likely not vinyl-ftp related - have you tried removing the node_modules directory and reinstalling all dependencies? it seems gulp-util is trying to require lodash but fails

**Comment by maxleistner** [comment]
Yeah your are right. This help a lot. Now it is working. Thanks
