### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by StuartMorris0** [morris/vinyl-ftp#24]
Hello,

We are trying to setup vinyl-ftp for quick deployment within our process. We separate our Development (Gulp Files, JS, LESS etc) then have our main site folder in a 'Site Files' folder. The setup for our deploy is as follows:

```
gulp.task( 'deploy', function() {
    var conn = ftp.create( {
        // username, host, pass etc.
        parallel: 1,
        maxConnections: 1,
        log:      gutil.log
    } );

    var globs = [
        '../Site Files/assets/**'
    ];

    // using base = '.' will transfer everything to /public_html correctly
    // turn off buffering in gulp.src for best performance

    return gulp.src( globs, { base: '.', buffer: false } )
        .pipe( conn.newer( '/public_html' ) ) // only upload newer files
        .pipe( conn.dest( '/public_html' ) );

} );
```

Every time we run the task we get an error:
CONN
READY
MSLD /Site Files
ERROR Error: read ECONNRESET
     at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26) (ECONNRESET)
DISC

Do you know what this could be?

We have a limit of 3 connections to the host, that is why we limit parallel/MaxConnections to 1 to stop the limit being hit a lot.

Thanks

**Comment by morris** [comment]
Have you tried a regular FTP client? Does that work? If yes, could you paste the log of your FTP client (in particular, anything MLSD/LIST related)?

**Comment by StuartMorris0** [comment]
Hey,

We can use Sublime SFTP (ftp mode) and FileZilla without any issues? Is that what you mean?

Thanks

**Comment by morris** [comment]
Yes exactly. Does the FileZilla log say "MLSD ..." at some point? Or LIST?

**Comment by StuartMorris0** [comment]
Hmm, the top status logging does not say much in FileZilla at all. I tried to enable logging to a file and this is the output

```
2015-07-18 00:38:13 9904 1 Status: Resolving address of DOMAINNAME
2015-07-18 00:38:13 9904 1 Status: Connecting to **IP**...
2015-07-18 00:38:13 9904 1 Status: Connection established, waiting for welcome message...
2015-07-18 00:38:13 9904 1 Response: 220 FTP server ready
2015-07-18 00:38:13 9904 1 Command: AUTH TLS
2015-07-18 00:38:13 9904 1 Response: 500 AUTH not understood
2015-07-18 00:38:13 9904 1 Command: AUTH SSL
2015-07-18 00:38:13 9904 1 Response: 500 AUTH not understood
2015-07-18 00:38:13 9904 1 Status: Insecure server, it does not support FTP over TLS.
2015-07-18 00:38:13 9904 1 Command: USER USERNAME
2015-07-18 00:38:13 9904 1 Response: 331 Password required for USERNAME
2015-07-18 00:38:13 9904 1 Command: PASS *********
2015-07-18 00:38:14 9904 1 Response: 230 Login successful. Username & password correct; FTP unlocked.
2015-07-18 00:38:14 9904 1 Command: OPTS UTF8 ON
2015-07-18 00:38:14 9904 1 Response: 200 UTF8 set to on
2015-07-18 00:38:14 9904 1 Status: Connected
2015-07-18 00:38:14 9904 1 Status: Retrieving directory listing...
2015-07-18 00:38:14 9904 1 Command: PWD
2015-07-18 00:38:14 9904 1 Response: 257 "/" is the current directory
2015-07-18 00:38:14 9904 1 Command: TYPE I
2015-07-18 00:38:14 9904 1 Response: 200 Type set to I
2015-07-18 00:38:14 9904 1 Command: PASV
2015-07-18 00:38:14 9904 1 Response: 227 Entering Passive Mode (79,170,44,20,219,222).
2015-07-18 00:38:14 9904 1 Command: MLSD
2015-07-18 00:38:14 9904 1 Response: 150 Opening ASCII mode data connection for MLSD
2015-07-18 00:38:14 9904 1 Response: 226 Transfer complete
2015-07-18 00:38:14 9904 1 Status: Directory listing of "/" successful

```

**Comment by morris** [comment]
Could you run "MLSD /Site Files" in FileZilla (Server -> Custom Command)? This might be an issue with the CWD, however I won't be able to fix that without a proper test server. Could you create a sandbox FTP user on your server for me to test? Otherwise I won't be able to help :(

**Comment by StuartMorris0** [comment]
It's difficult to try the server custom command, as the file structure would be different for FileZilla. Not sure if what the server command file path it would be expected.

I could probably set you up an FTP account on a different domain to a sub directory of public_html would that work?

**Comment by StuartMorris0** [comment]
I've emailed you an FTP account to a different domain on the same shared platform, so hopefully you can test with that. It should be unlocked for 24 hours. I have to come offline now, will be back tomorrow. Thanks for the help morris!

**Comment by morris** [comment]
Not a vinyl-ftp issue; the following script causes the same connection reset, however only in the reporters network. @StuartMorris0 please recreate the issue at https://github.com/mscdex/node-ftp (see my e-mail for directions).

```
var FTP = require( 'ftp' );

var client = new FTP();

client.on( 'ready', onReady );

function onReady() {

	client.list( '/', onList );

}

function onList( err, list ) {

	if ( err ) console.log( err.stack );
	else console.log( list );

}

client.connect( {
	user: '...',
	password: '...',
	host: '...',
	debug: console.log.bind( console )
} );
```

**Comment by StuartMorris0** [comment]
Reference:
https://github.com/mscdex/node-ftp/issues/126

**Comment by PinkPandaAU** [comment]
I'm having the exact same issue - any solution for this?
