### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by Djuka** [morris/vinyl-ftp#51]
Now I realise this might not be the issue of vinyl-ftp, but I am having a hard time understanding what is happening here. I have FTP configuration:
``` javascript
// config-ftp.js
module.exports = {
    host: 'ftp.xxxx.xx',
    user: 'yyyy@xxxx.xx',
    password: 'somepwd',
    parallel: 10,
    secure: true,
    secureOptions: true,
    log: require('gulp-util').log
};
```

Here is the task (just in case):
``` javascript
var gulp = require('gulp'),
    ftp = require('vinyl-ftp'),
    config = require('config-ftp');

gulp.task('deploy', function () {

    var conn = ftp.create(config);

    return gulp.src('build/**', {
            base: './',
            buffer: false
        })
        .pipe(conn.newer('/'))
        .pipe(conn.dest('/'));

});
```

This is the error I get:
``` javascript
ERROR Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1016:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:585:8) (UNABLE_TO_VERIFY_LEAF_SIGNATURE)
```

**Comment by morris** [comment]
Looks like TLS is not available or misconfigured at the target host. Does it work with regular FTP clients when forcing a TLS connection?

**Comment by mnewmedia** [comment]
I have the same issue and it works with regular ftp client.

server configuration vsftpd:
```
ssl_tlsv: enabled
ssl_v2: disabled
ssl_v1: disabled
certificates: from letsencrypt
allow_anon_ssl: false
allow_anon: false
pasv_enable: true
pasv_adress: wan-ip
```
maybe with trial and error changing the server settings, I will find out whats causing the problem.
