### ISSUE TITLE
Can't create directory: File exists

### ISSUE THREAD

**Issue by yanickrochon** [morris/vinyl-ftp#54]
While saving two new files in the same new directory, the event fired two parallel tasks that went on to upload these two new files, which produced this output 

```
[12:10:56] CONN 
[12:10:56] CONN 
[12:10:56] READY
[12:10:56] MLSD  /wp-content/themes/foo/languages
[12:10:56] READY
[12:10:56] MLSD  /wp-content/themes/foo/languages
[12:10:56] MLSD  /wp-content/themes/foo
[12:10:56] MLSD  /wp-content/themes/foo
[12:10:56] MLSD  /wp-content/themes
[12:10:57] MLSD  /wp-content/themes
[12:10:57] MKDIR /wp-content/themes/foo/languages
[12:10:57] PUT   /wp-content/themes/foo/languages/fr_FR.mo
[12:10:57] MKDIR /wp-content/themes/foo/languages
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Can't create directory: File exists
    at makeError (/path/to/www/node_modules/vinyl-ftp/node_modules/ftp/lib/connection.js:1067:13)
    at Parser.<anonymous> (/path/to/www/node_modules/vinyl-ftp/node_modules/ftp/lib/connection.js:113:25)
    at emitTwo (events.js:87:13)
    at Parser.emit (events.js:172:7)
    at Parser._write (/path/to/www/node_modules/vinyl-ftp/node_modules/ftp/lib/parser.js:59:10)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Parser.Writable.write (_stream_writable.js:207:11)
    at Socket.ondata (/path/to/www/node_modules/vinyl-ftp/node_modules/ftp/lib/connection.js:273:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

It would be nice if a warning would be thrown, but the code could recuperate gracefully after this kind of error. It is silly to abort saying "I cannot copy the file here, because the destination folder exists."

Just a thought.

**Comment by morris** [comment]
Definitely silly and not intended.

**Comment by morris** [comment]
This is the result of a rare race condition, should be fixed now.

**Comment by yanickrochon** [comment]
Excellent! Thanks!
