### ISSUE TITLE
files are not getting uploaded in the server

### ISSUE THREAD

**Issue by amitabhaghosh197** [morris/vinyl-ftp#57]
I am using vinyl-ftp . 

My gulpfile.js code is:
```

var gutil = require('gulp-util');
var ftp = require('vinyl-ftp');

gulp.task( 'deploy-dev', function () {
 
    var conn = ftp.create( {
        host:     'my_server_host_name',
        user:     'my_server_username',
        password: 'my_server_password',
        parallel: 5,
        log:      gutil.log
    } );
 
    var globs = [
        'assets/**',
        '!node_modules/**',
        '!assets/img/**',
        '!assets/bower_componets/**',
        '!assets/dist/**'
    ];
 
    // using base = '.' will transfer everything to /public_html correctly 
    // turn off buffering in gulp.src for best performance 
 
    return gulp.src( globs, { base: 'assets/', buffer: false } )
        .pipe( conn.newer( '/public_html/demos/P-09-Sakha/html' ) ) // only upload newer files 
        .pipe( conn.dest( '/public_html/demos/P-09-Sakha/html' ) );
 
} );

// Default Task
gulp.task('default', [ 'scripts','css','watch', 'deploy-dev']);
```

But it is throwing error: 
```
[16:58:12] Using gulpfile E:\xamp\htdocs\projects\P-09-sakha\html\gulpfile.js
[16:58:12] Starting 'scripts'...
[16:58:12] Starting 'css'...
[16:58:12] Starting 'watch'...
[16:58:12] Finished 'watch' after 74 ms
[16:58:12] Starting 'deploy-dev'...
[16:58:12] CONN
[16:58:12] CONN
[16:58:14] ERROR Error: Sorry, cleartext sessions are not accepted on this serve
r.
    at makeError (E:\xamp\htdocs\projects\P-09-sakha\html\node_modules\vinyl-ftp
\node_modules\ftp\lib\connection.js:1067:13)
    at Parser.<anonymous> (E:\xamp\htdocs\projects\P-09-sakha\html\node_modules\
vinyl-ftp\node_modules\ftp\lib\connection.js:113:25)
    at emitTwo (events.js:87:13)
    at Parser.emit (events.js:172:7)
    at Parser._write (E:\xamp\htdocs\projects\P-09-sakha\html\node_modules\vinyl
-ftp\node_modules\ftp\lib\parser.js:59:10)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at Parser.Writable.write (_stream_writable.js:214:11)
    at Socket.ondata (E:\xamp\htdocs\projects\P-09-sakha\html\node_modules\vinyl
-ftp\node_modules\ftp\lib\connection.js:273:20)
    at emitOne (events.js:77:13) (421)
[16:58:14] DISC
[16:58:14] ERROR Error: Sorry, cleartext sessions are not accepted on this serve
r.
    at makeError (E:\xamp\htdocs\projects\P-09-sakha\html\node_modules\vinyl-ftp
\node_modules\ftp\lib\connection.js:1067:13)
    at Parser.<anonymous> (E:\xamp\htdocs\projects\P-09-sakha\html\node_modules\
vinyl-ftp\node_modules\ftp\lib\connection.js:113:25)
    at emitTwo (events.js:87:13)
    at Parser.emit (events.js:172:7)
    at Parser._write (E:\xamp\htdocs\projects\P-09-sakha\html\node_modules\vinyl
-ftp\node_modules\ftp\lib\parser.js:59:10)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at Parser.Writable.write (_stream_writable.js:214:11)
    at Socket.ondata (E:\xamp\htdocs\projects\P-09-sakha\html\node_modules\vinyl
-ftp\node_modules\ftp\lib\connection.js:273:20)
    at emitOne (events.js:77:13) (421)
[16:58:14] DISC
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Sorry, cleartext sessions are not accepted on this server.
    at makeError (E:\xamp\htdocs\projects\P-09-sakha\html\node_modules\vinyl-ftp
\node_modules\ftp\lib\connection.js:1067:13)
    at Parser.<anonymous> (E:\xamp\htdocs\projects\P-09-sakha\html\node_modules\
vinyl-ftp\node_modules\ftp\lib\connection.js:113:25)
    at emitTwo (events.js:87:13)
    at Parser.emit (events.js:172:7)
    at Parser._write (E:\xamp\htdocs\projects\P-09-sakha\html\node_modules\vinyl
-ftp\node_modules\ftp\lib\parser.js:59:10)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at Parser.Writable.write (_stream_writable.js:214:11)
    at Socket.ondata (E:\xamp\htdocs\projects\P-09-sakha\html\node_modules\vinyl
-ftp\node_modules\ftp\lib\connection.js:273:20)
    at emitOne (events.js:77:13)
```

Can't find the error. I don't know why it is throwing "cleartext sessions are not accepted on this serve
r.", my all credentials are correct

Your help in this regard is highly solicited.

Thanks in advance

**Comment by morris** [comment]
Looks like your server requires secure sessions. Try using the `secure: true` option.
