### ISSUE TITLE
Error: Unable to make data connection at Socket.<anonymous>

### ISSUE THREAD

**Issue by StevenOosterbeek** [morris/vinyl-ftp#65]
Sometimes I get the following error while using VinylFtp with Gulp.

` Error: Unable to make data connection at Socket.<anonymous (.../node_modules/ftp/lib/connection.js:935:10)`

These are my connection options - where the host, user and password are filled in during the request of course.

```
VinylFtp {
  config:
   { parallel: 3,
     maxConnections: 5,
     log: null,
     timeOffset: 0,
     idleTimeout: 100,
     password: '',
     reload: false,
     host: '',
     user: '' },
  queue: [],
  connectionCount: 0,
  idle: [],
  idleTimer: null }
```

Is this a bug within the module or am I doing something wrong?

Cheers and thanks in advance!

**Comment by StevenOosterbeek** [comment]
I also get the following error sometimes:

```
TypeError: Cannot read property 'filter' of undefined
    at VinylFtp.module.exports.vinylFiles (.../node_modules/vinyl-ftp/lib/ftp.js:432:15)
```

**Comment by StevenOosterbeek** [comment]
@morris, is this something you will look into in the near future?

**Comment by morris** [comment]
I hope to, however since locally my tests are passing it's hard to reproduce. Could you add relevant `npm ls`, OS, FTP server software details to the issue? Ideally you'd create an FTP sandbox user for me to test on your specific server. Most bugs in vinyl-ftp are related to specific FTP server quirks, unfortunately.

**Comment by StevenOosterbeek** [comment]
Thank you for your response and sorry for my late response. To be honost we would rather not create a sandbox FTP for you at the moment due to various reasons. Here are however some more details as you requested.

**OS**: OS X El Capitan, 10.11.5
**FTP software on server**: ProFTPD - v1.3.5b

The ```npm ls``` gives an enourmes list of modules, and an error which looks like it could have to do something with the error I get:

```
npm ERR! extraneous: parallel-transform@0.2.2 ../node_modules/parallel-transform
```

It is however also possible to receive the whole list if you want?

**Comment by StevenOosterbeek** [comment]
@morris - we are still encountering the problem almost every day, so could you please take a bit of your time to find out what the problem could be? We couldn't find out ourselves so far, so your help will be appreciated a lot!

**Comment by TimKohler** [comment]
@morris  - We are also experiencing this issue.  We are using vinyl-ftp to deploy to ms azure app service (using the ftp credentials/url provided in the azure portal).  This is happening very, very frequently.  

Any help would be super, super appreciated!

**Comment by morris** [comment]
I'm still not able to reproduce this. The "cannot read property filter of undefined" issue is likely caused by https://github.com/mscdex/node-ftp/issues/170 - however that would require an ABOR command. Are you issuing ABOR commands somehow?

If you want to help: The `Unable to make data connection at Socket.<anonymous` is likely https://github.com/mscdex/node-ftp specific. Could you try reproducing that by only using node-ftp, not vinyl-ftp? That would certainly help in locating the root cause.

Sorry to disappoint, I just can't reproduce this, at least not in reasonable time limits...

**Comment by jcommaret** [comment]
I have the same problem, from my computer at my office, but the bug didn't appear yesterday while i was at home, using exactly the same computer. 
This problem could be due to :
- micro-cuts from the server
- micro-cuts from the ISP
And all file transferts related problems.
![capture d ecran 2017-02-08 a 12 24 55](https://cloud.githubusercontent.com/assets/242889/22735379/bbc916d0-edf9-11e6-9666-0568c0f76cea.png)

**Comment by sylvain261** [comment]
Same issue "Unable to make data connection". error occur very frequently so the package wich claim "Often performs better than your favorite desktop FTP client." is not usable for us.

**Comment by MilllerTime** [comment]
I'm seeing the same issue as the rest of these folks, and it occurs nearly every time I try.

I'm running Node 6.11.3 on Windows 10, and the remote FTP server is running on IIS 8.5.

I've also experimented with the `parallel`, `maxConnections`, and `reload` options to no avail.

**Comment by MilllerTime** [comment]
Sorry for the double comment, but I just noticed another error was mentioned earlier in this thread that I am also seeing sometimes. Here's the stack trace I'm seeing:

```
TypeError: Cannot read property 'filter' of undefined
    at VinylFtp.vinylFiles (...\node_modules\vinyl-ftp\lib\ftp.js:433:15)
    at onFiles (...\node_modules\vinyl-ftp\lib\ftp.js:409:24)
    at ...\node_modules\ftp\lib\connection.js:431:14
    at ...\node_modules\ftp\lib\connection.js:887:7
    (...deeper into ftp lib)
```

Note that I am not personally issuing, nor am I seeing any ABOR commands in my logs.

Additionally, I'm seeing yet another error sometimes, from a different file:

```
TypeError: Cannot read property 'forEach' of null
    at ...\node_modules\vinyl-ftp\lib\cache.js:42:15
    at final (...\node_modules\vinyl-ftp\lib\ftp.js:416:6)
    at onFiles (...\node_modules\vinyl-ftp\lib\ftp.js:407:24)
    at ...\node_modules\ftp\lib\connection.js:427:14
    (...deeper into ftp lib)
```

@morris If you think these errors warrant a separate issue, I can certainly do that for organization. However, the primary error I'm seeing is the topic of this issue.

I do want to stress that on a very rare occasion the upload works perfectly, and uploading via FileZilla always works without issue. So I don't believe my code itself is a problem, or the server. I've tried to create a reduced test case, shown here. I'm simply uploading the contents of a single directory. This code only ever succeeded once, and has failed with the various errors noted above a couple dozen times.

```js
const BUILD_PATH = './build/dist/';
const REMOTE_ROOT_PATH = '/www';
const FTP_CONFIG = {
  host: '*****',
  port: 21,
  secure: true,
  user: '*****',
  password: '*****',
  parallel: 5,
  maxConnections: 5,
  log: gutil.log,
  // Server is using a self signed certificate.
  secureOptions: { rejectUnauthorized: false }
};

gulp.task( 'deploy', () => {
  const connection = ftp.create( FTP_CONFIG );
  const glob = BUILD_PATH + '**';
  return gulp.src( glob, { base: BUILD_PATH, buffer: false } )
                    .pipe( connection.dest( REMOTE_ROOT_PATH ) );
} );
```

I would have attempted replicating this issue with `node-ftp` alone, but dealing with a recursive directory structure is so much easier when one can glob files - a huge perk of this library! Still, I'll see if I can find some time to try `node-ftp` and will report back with any findings there.

Anyhow, thanks for all the effort you've put into this project so far!

**Comment by cassmtnr** [comment]
Anything on this? I've got the same errors, but it's just 1-2 times per day, if I retry like 2-3 times it works.

**Comment by WhereJuly** [comment]
@morris

First, thank you for the great utility :) Very convenient.

Here what I found after hangin on `Unable to make data connection at Socket.<anonymous` error for some hours:
- This is only an issue for the one of my hosting providers;
- Making the same upload to the same hosting via FileZilla faces aborts and reconnects in ~1% of cases (~220 aborted transfers for ~22,000 files) showing FileZilla `Wrong password` error;
- Making the same FileZilla upload to the other hosting shows no errors (FTP or SFTP);
- Nevertheless on the second hosting `vinyl-ftp` crashes with `Error: Timed out while making data connection  at Timeout.<anonymous> (myprojectpath\node_modules\ftp\lib\connection.js:901:12)`.

Thoughts:

The initial `Unable to make data connection` error is gone and I believe this is due to the hoster issue, not `vinyl-ftp`. I asked their tech support. If they answer something sound I add here.

The second error `Timed out while making data connection`, I suspect, happens when (my guesses follow):
- `vinyl-ftp` tries to read files to the buffer AND the number of files is that huge (22,000 in my case) that 
- some internal timeout (`vinyl-ftp` or Node ftp module one) expires 
- and that timeout is not controlled by `vinyl-ftp` 's ` idleTimeout` which I tried to set from 30000 to 120000 with no effect.
