### ISSUE TITLE
Can't create directory - Error: Access is denied.

### ISSUE THREAD

**Issue by sumedhmeshram** [morris/vinyl-ftp#73]
**Here is my Gulp file.**

'use strict';

var gulp = require( 'gulp' );
var gutil = require( 'gulp-util' );
var ftp = require( 'vinyl-ftp' );
var paths = gulp.paths;

var conn = ftp.create( {
        host:     'myhost', 
        user:     'usr',
        password: 'pwd',
        port:     '1001',
        parallel: 10,
        log:      gutil.log
    } );

 var globs = [ './homepage/**'];

gulp.task( 'deploy', function () {

```
// using base = '.' will transfer everything to /public_html correctly 
// turn off buffering in gulp.src for best performance 

return gulp.src( globs, { base: '.homepage', buffer: false } )
    .pipe( conn.newer( '/homepage' ) ) // only upload newer files 
    .pipe( conn.dest( '/home123' ) );
```

} );

**Giving this error**

Microsoft Windows [Version 10.0.14393](c) 2016 Microsoft Corporation. All rights reserved.                                                              

E:\Day Users\SumedhMeshram\Official\Projects\32-ChildDayCare\srcbit\CDC.Web>gulp deploy  
[20:02:39] Using gulpfile E:\Day Users\SumedhMeshram\Official\Projects\32-ChildDayCare\srcbit\CDC.Web\gulpfile.js 
[20:02:39] Starting 'deploy'...  
[20:02:39] CONN  
[20:02:39] CONN  
[20:02:39] CONN  
[20:02:39] CONN  
[20:02:41] READY  
[20:02:41] MLSD  /homepage  
[20:02:41] READY  
[20:02:41] MLSD  /  
[20:02:41] READY  
[20:02:41] MLSD  /homepage/fonts  
[20:02:41] READY  
[20:02:41] MLSD  /homepage/css  
[20:02:41] LIST  /homepage  
[20:02:42] LIST  /  
[20:02:42] LIST  /homepage/fonts  
[20:02:42] LIST  /homepage/css  
[20:02:42] DISC  
[20:02:43] MKDIR /homepage  
[20:02:43] MLSD  /homepage/images  
[20:02:43] DISC  
[20:02:43] 'deploy' errored after 4.41 s  
[20:02:43] Error: Access is denied.    

```
at makeError (E:\Day Users\SumedhMeshram\Official\Projects\32-ChildDayCare\srcbit\CDC.Web\node_modules\vinyl-f
```

tp\node_modules\ftp\lib\connection.js:1067:13)  
    at Parser.<anonymous> (E:\Day Users\SumedhMeshram\Official\Projects\32-ChildDayCare\srcbit\CDC.Web\node_module
s\vinyl-ftp\node_modules\ftp\lib\connection.js:113:25)  
    at emitTwo (events.js:87:13)  
    at Parser.emit (events.js:172:7)  
    at Parser._write (E:\Day Users\SumedhMeshram\Official\Projects\32-ChildDayCare\srcbit\CDC.Web\node_modules\vin
yl-ftp\node_modules\ftp\lib\parser.js:59:10)  
    at doWrite (_stream_writable.js:300:12)  
    at writeOrBuffer (_stream_writable.js:286:5)  
    at Parser.Writable.write (_stream_writable.js:214:11)  
    at Socket.ondata (E:\Day Users\SumedhMeshram\Official\Projects\32-ChildDayCare\srcbit\CDC.Web\node_modules\vin
yl-ftp\node_modules\ftp\lib\connection.js:273:20)  
    at emitOne (events.js:77:13)  
[20:02:43] DISC  
[20:02:44] LIST  /homepage/images  
[20:02:45] MLSD  /homepage/js  
[20:02:45] LIST  /homepage/js  
[20:02:46] DISC
[20:02:44] LIST  /homepage/images  
[20:02:45] MLSD  /homepage/js  
[20:02:45] LIST  /homepage/js  
[20:02:46] DISC                                                                                                   

E:\Day Users\SumedhMeshram\Official\Projects\32-ChildDayCare\srcbit\CDC.Web>           

**Here is the logs when I am connecting through FTP client which is working fine.**

FireFTP 2.0.28 'Nature Boy' designed by Mime Čuvalo in Croatia

SSH component is ported from Paramiko 1.7.7.1, created by Robey Pointer

220 Microsoft FTP Service
       USER usr
331 Password required
       PASS (password not shown)
230 User logged in.
       FEAT
211-Extended features supported:
LANG EN*
UTF8
AUTH TLS;TLS-C;SSL;TLS-P;
PBSZ
PROT C;P;
CCC
HOST
SIZE
MDTM
REST STREAM
211 END
       PWD
257 "/onlinechildcare" is current directory.
       TYPE A
200 Type set to A.
       PASV
227 Entering Passive Mode (108,168,203,227,243,142).
       LIST
150 Opening ASCII mode data connection.
226 Transfer complete.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.
       NOOP
200 NOOP command successful.

Please help, i am trying since 2 hrs now.

**Comment by sumedhmeshram** [comment]
Cany someone update on this please.

**Comment by morris** [comment]
Likely some permissions are missing on your subfolders. The second log only connects to the FTP server, it does not retrieve directory listings.
