### ISSUE TITLE
Could not connect with

### ISSUE THREAD

**Issue by bdjunayed** [morris/vinyl-ftp#81]
I made successful conn with these bellow code. But, it show error while connecting to another hosting.

[14:55:19] ERROR Error: Hostname/IP doesn't match certificate's altnames: "Host: banglatyping.com. is not in the cert's altnames: DNS:*.prod.iad2.secureserver.net, DNS:prod.iad2.secureserver.net"

throw er; // Unhandled 'error' event

gulp.task( 'deploy', function () {
    var conn = ftp.create( {
        host:     '***',             
        user:     '***',      
        password: '***',
        parallel: 10,
        log:      gutil.log,
} );

   return gulp.src( '_site/**', { base: './_site/', buffer: false } )
        .pipe( conn.newer( '/ho' ) ) // only upload newer files 
        .pipe( conn.dest( '/ho' ) );
} );

**Comment by morris** [comment]
The error indicates that something with TLS went wrong, which is only used with `secure: true`. I wonder how this could be since `secure` is not in your settings. Which Node.js version are you running? In any case this does not look like vinyl-ftp related; the server's TLS configuration seems to be invalid.

**Comment by bdjunayed** [comment]
Thank you for your kind attn, my npm is 4.1.2, with the above deploy task code the output is as bellow(It does not show me the previous error code!):

**Error code without the secure settings:**
[19:06:53] Starting 'deploy'...
[19:06:53] CONN
[19:06:53] CONN
[19:07:05] ERROR Error: read ECONNRESET
    at exports._errnoException (util.js:1029:11)
    at TCP.onread (net.js:575:26) (ECONNRESET)
[19:07:05] DISC
[19:07:05] ERROR Error: read ECONNRESET
    at exports._errnoException (util.js:1029:11)
    at TCP.onread (net.js:575:26) (ECONNRESET)
[19:07:05] DISC
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1029:11)
    at TCP.onread (net.js:575:26)


**Error code with the bellow secure settings:**
`        secure:   true,
        secureOptions: {
            rejectUnauthorized: false
        }`

[19:10:15] Starting 'deploy'...
[19:10:15] CONN
[19:10:15] CONN
[19:10:26] ERROR Error: read ECONNRESET
    at exports._errnoException (util.js:1029:11)
    at TLSWrap.onread (net.js:575:26) (ECONNRESET)
[19:10:26] DISC
[19:10:29] ERROR Error: read ECONNRESET
    at exports._errnoException (util.js:1029:11)
    at TLSWrap.onread (net.js:575:26) (ECONNRESET)
[19:10:29] DISC
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1029:11)
    at TLSWrap.onread (net.js:575:26)
